### ISSUE TITLE
volumenes fuera de contexto?

### ISSUE THREAD

**Issue by vk496** [dsevilla/bdge#2]
Como va todo @dsevilla ? :)

https://github.com/dsevilla/bdge/blob/b957fd0fa1b51fb643ac7af714dc0d6a74a39213/pig-hive/docker-compose-pig.yml#L14

Me ha llamado mucho la atención esto. Funciona realmente?

Que yo sepa, Docker fuerza que la ruta desde donde lo ejecutas sea su contexto. Y cualquier cosa fuera de él, te echa para atrás. Ejemplo:

```bash
$ docker run --rm -v ..:/ext:ro -ti ubuntu                                                                                                              11s  11:49:56
docker: Error response from daemon: create ..: ".." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```
No deja ni siquiera directorios relativos al contexto.

Si es para el directorio actual, el 'truqui' suele usar tirar de `$PWD`

**Comment by vk496** [comment]
PD: Si esto era parte de puntos extra, borro la issue y aquí no ha pasado nada..... :smile_cat:

**Comment by dsevilla** [comment]
Hola!

Encantado de que le eches un ojo a lo que tengo por aquí! :)

Pues sí, efectivamente no deja poner rutas relativas porque esto se envía al demonio de docker. Sin embargo, sí que no da problemas al ejecutarlo dentro de un docker-compose, ya que éste hará lo necesario para fijar el directorio actual y convertir los paths relativos a absolutos a partir de la ruta de llamada a `docker-compose` (o `docker compose` en las versiones modernas). Yo lo he venido utilizando sin problemas, y de hecho así está en los otros compose de otros directorios de prácticas relativos a otras herramientas.

No obstante, también te digo que hace años que esa parte no la ejercito, no da tiempo a darla muchas veces y no sé siquiera si esos contenedores de pig estarán funcionando. La tecnología de pig también se ha ido abandonando en favor de hive o incluso directamente spark. Lo he dejado ahí por motivos históricos.

Un saludo!
d.
